### PR TITLE
Create blog-post-workflow.yml

### PR DESCRIPTION
**Pull request by hrishikeshp7**
This RSS Feed is of my blog you can change this with your Hashnode Blog

### CODE REVIEW

**Comment by hrishikeshp7** [comment]
Okay I found your RSS Feed url :- https://kritika-pattalam.hashnode.dev/rss.xml
just replace this with the other one and you will be done . The workfow will run every 8 hours to check for any new content on your hashnode blog

**Comment by kritika-pattalam** [comment]
@hrishikeshp7 : This is a good one. It was on my to-do list. Thanks

**Comment by kritika-pattalam** [comment]
This is a good one. This was in my to-do list.

**Comment by hrishikeshp7** [comment]
@kritika-pattalam  nice , Felt nice to help .

**Pull request merged**
